"""Frozen final K230 deployment configuration."""

CAMERA_ID = 1
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_ROI = (160, 90, 960, 540)
TARGET_SIZE = 256
FOCUS_POSITION = 275

KEY_PHYSICAL_PIN = 21
KEY_GPIO = 21
KEY_DEBOUNCE_MS = 30
IDLE_POLL_MS = 20

LIGHT_CAPTURE_DELAY_MS = 2000
LIGHT_ON_DURATION_MS = 5000

ALGORITHM_ROOT = "/sdcard/texture_structure_tensor_v1"
RESULT_DIRECTORY = "/sdcard/data_touch_results"
RESULT_TXT = RESULT_DIRECTORY + "/u_curve.txt"

EXPECTED_BACKEND = "FUSED_SPAN_QUERY_NATIVE_C"
